specifications:
  onchain-wallet:    
    settings:
      currency:
        - cad, usd, crc, inr
        - units must reflect in all sections of the app apart from market
        - check against send -> amount & recieve -> request payment -> amount
      unit: 
        - BTC
        - sats
        - units must reflect in all sections of the app that require input 
          or display of amounts
        - bip21 invoice must always have amount in BTC but value can be entered as any currency
      testnet:
        - possible bugs:
          - ensure that wallet state is properly managed while switching between networks
          - try switching networks in-between sync
      rbf:
        - if set to ON - send should show disable in advanced
        - if set to OFF - send should show enable in advanced
        - only send + rbf-enabled txs should have bump fee in transaction view
      pin:
        - once set, becomes required
        - add warning on homepage to set pin
      fee:
        - select default fee rate
        - uses mempool.bullbitcoin.com (privacy)
      broadcast:
        - must be able to decode and broadcast both psbt and tx-hex
        - must show transaction breakdown for approval before broadcasting
        - where possible, check inputs and outputs against address-book
      electrum:
        - default node = bullbitcoin.com
        - secondary node = blockstream.info
        - custom node = user private node:
          - notify user of privacy concerns (usage of mempool.bullbitcoin.com)
        - if a new node is selected it must become the default
        advanced:
          - stop-gap = 20 (default):
            - will be auto-updated based on how wallets address gap
          - timeout = 5s
          - retry = 5s
        - mainnet/testnet node address input
      theme:
      tor: (pending)
          - connect via external tor
          - **tor daemon
    key:
      new:
        - default 12 word seed created on start up w/o passphrase:
          - 84' segwit only
        - option for additional new 12/24 word seed w/passphrase:
          - show wallet selection to select script type
      recover:
        - 12/24 word recovery with passphrase
        - aid user in typing seed by using the 2048 bip39 wordlist to filter
        - show wallet selection to allow choice of script type
      import:
        xpub:
          - xpub w/o key-origin:
            - 44' legacy wallet only
          - xpub w/key-origin:
            - show wallet selection for script types
          - slip-132-pub:
            - xpub = 44'
            - ypub = 49'
            - zpub = 84'
          - qr-scan:
        coldcard:
          - upload file
          - show wallet selection
          - validate first address
          - show instructions
      advanced: (test)
        - import a wallet given a private/public key dump (partial descriptors, xpubs, wif)
      key-chain: (review)
        - seed:
          - show list of seeds from which passphrase/script wallets can be derived
        - xpub:
          - show list of master xpubs from which script wallets can be derived
    wallet:
      settings:
        label:
          - update
        key-type:
        stats:
          - total received
          - total sent
        backup:
          - view backup
          - verify
        wallet-details:
          - fingerprint
          - xpub
          - public descriptor
          - script type
        address-book:
          - deposit:
            - sort by highest to lowest index
            - show active utxo's first, then unused and finally used.
          - change: 
          - detail: clicking either deposit|change opens address detail
            - ensure it all fits in one page
            - show qr, address, copy, label
            - do not show qr or allow copying address if used
        accounting:
          - total historical volume
          - total number of transactions
          - export transactions csv
        label-import-export (bip329): 
          - select destination of label file.
          - encrypt/decrypt using key derived from seed using bip85
          - standard key path: 83696968'/128169'/64'/{index}' (review)
          - import:
            - attempt to readfile:
              - if encrypted, derive key and attempt decrypt
          - export:
            - default enable encryption, allow disable
            - filename-format: `$index-hex($walletOrigin)`
        delete:
          - only delete wallet if seed has other wallets
          - delete both wallet and seed if only one wallet exists for the seed  
      sync:        
        - sync selected wallet first, then sync others asynchronously      
      transactions:        
        - local model is built based on bdk model
        - outputs:
          - new transactions must scan and record their outputs and add 
            them to the address-book
          - old transactions need not repeat the process
        - label: 
          - update in tx label must affect the labels of the output addresses 
            in the address-book
          - for send transactions, associated change must inherit the tx label
          - for recieve transactions, tx label must be inherited from deposit 
            address
        - timestamps:
        - amounts:
          - for send, amount should be amount sent to the recipient
          - for recieve, amount should be the amount we recieved
        - fee:
          - fee should be shown separately       
      recieve:    
        - display QR for address
        - display address with button to copy to clipboard
        - update label:
          - must affect associated transactions
        - create-invoice (bip21):
          - if an invoice is created, the description should by default match 
            the label, if updated, the label should be updated
          - after creating an invoice qr and address field must update
        - generate-new:
          - users can freely generate new addresses
          - warnings are issued when a gap of 5 is crossed
          - at a gap > 20, electrum stop-gap is updated        
      send:
      - address:
          - display in short form, edit in full form
          - scannable via QR
      - bip21 invoice must populate:
        - address
        - amount
        - description
      - amount:
        - input in sats/BTC
        - formatting:
          - sats = *,***follows
          - BTC = *,***.********
      - fee:
        - show fee selection based on mempool api
        - show estimated CAD value
      - advanced:
        - send full balance:
          - disable amount field
          - disable manual coin selection
          - notify users that frozen utxos will also be used (pending)
        - coin selection:
          - display available utxos with balance and labels
          - show total amount of utxos selected
          - **allow only selecting as many as is enough for the amount being sent
        - toggle rbf:
      - summary:
        - show a breakdown of the transaction before confirming
      - complete:
        - show a complete screen
        - initiate sync after a short delay
        - **view transaction detail: naviagate to the transaction page
        - done: naviagate back home
  market:
    auth:
        register-popup:
          - ask user to register or continue using only wallet
        sign-up:
          - email
          - password
          - confirm password
        login:
          - email
          - password 
    services:
      kyc:
        status:
        country:
          - country
          - currency
          - language
        email:
          - email
        full-name:
          - first name
          - last name
        phone:
          - country
          - number
          - verify:
            - resend
            - recieve phone call
            - edit number
        residential:
          - search address:
          - manual:
        dob:
          - day
          - month
          - year
        occupation:
          - industry:
            - search:
            - manual:
          - job title:
            - search:
            - manual:
      account-deposits:
        post:
        wire:
        e-transfer:
      account-withdrawals:
        wire:
        e-transfer:
      bitcoin-buy:
      bitcoin-sell:
      bitcoin-payments:
    account:
  ln-wallet:

figma:
  market: https://www.figma.com/file/GbothzdXmLPrf3bgQe5zTr/MVP---Transaction?type=design&node-id=3344-3730&mode=design&t=mCOVo1hem2aa6isN-4