name: Analyze

on:
  push:
    branches:
      - main

jobs:
  analyze:
    name: Run Flutter Analyze
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.5.3'

    - name: Install dependencies
      run: flutter pub get

    - name: Run Flutter Analyze
      run: |
        if flutter analyze --no-fatal-warnings | grep "warning"; then
          exit 1
        fi
